dataloader:
  image_height: 256
  image_width: 512
  batch_size: 1
  img_channels: 3
  p: 0.5

model:
  epochs: 200
  learning_rate: 0.0002
  beta1: 0.5
  beta2: 0.999
  device: mps

weight:
  Conv:
    mean: 0.0
    std: 0.02

  BatchNorm:
    mean: 1.0
    std: 0.02

  constant:
    bias: 0.0
