RAW_DATA_PATH = "./data/raw/"
PROCESSED_DATA_PATH = "./data/processed/"
TRAIN_CHECKPOINTS = "./checkpoints/train_models/"
LAST_CHECKPOINTS = "./checkpoints/best_model/"
TRAIN_IMAGES = "./outputs/train_images/"
TEST_IMAGES = "./outputs/test_images/"
GIF_PATH = "./outputs/train_gif/"
